# Generated by Django 6.0 on 2026-01-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('couple_name', models.CharField(max_length=255)),
                ('wedding_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('map_link', models.URLField()),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Les Mariés',
                'verbose_name_plural': 'Les Mariés',
            },
        ),
    ]
