# Generated by Django 6.0 on 2026-01-19 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
