# Generated by Django 6.0 on 2026-01-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rsvp_qr_code_rsvp_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='token',
        ),
    ]
