# Generated by Django 6.0 on 2026-01-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rsvp_qr_code_rsvp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
